# Copy to application-private.properties and fill the values for your environment.
ENTERPRISE_DEV_SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_PASSWORD=
ENTERPRISE_DEV_SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SLAVE_PASSWORD=
ENTERPRISE_DEV_SPRING_RABBITMQ_PASSWORD=
ENTERPRISE_DEV_SPRING_BOOT_ADMIN_CLIENT_PASSWORD=
ENTERPRISE_DEV_WX_MP_SECRET=
ENTERPRISE_DEV_WX_MINIAPP_SECRET=
ENTERPRISE_DEV_JUSTAUTH_TYPE_DINGTALK_CLIENT_SECRET=
ENTERPRISE_DEV_JUSTAUTH_TYPE_WECHAT_ENTERPRISE_CLIENT_SECRET=
ENTERPRISE_DEV_JUSTAUTH_TYPE_ALIPAY_CLIENT_SECRET=
ENTERPRISE_LOCAL_SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_PASSWORD=
ENTERPRISE_LOCAL_SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SLAVE_PASSWORD=
ENTERPRISE_LOCAL_SPRING_RABBITMQ_PASSWORD=
ENTERPRISE_LOCAL_SPRING_BOOT_ADMIN_CLIENT_PASSWORD=
ENTERPRISE_LOCAL_WX_MP_SECRET=
ENTERPRISE_LOCAL_WX_MINIAPP_SECRET=
ENTERPRISE_LOCAL_JUSTAUTH_TYPE_DINGTALK_CLIENT_SECRET=
ENTERPRISE_LOCAL_JUSTAUTH_TYPE_WECHAT_ENTERPRISE_CLIENT_SECRET=
ENTERPRISE_LOCAL_JUSTAUTH_TYPE_ALIPAY_CLIENT_SECRET=
ENTERPRISE_BASE_MYBATIS_PLUS_ENCRYPTOR_PASSWORD=
ENTERPRISE_BASE_ENTERPRISE_TRADE_EXPRESS_KD_NIAO_API_KEY=
