# -*- coding: utf-8 -*-
"""一次性补丁：将 gen_front.py 的 index_vue 替换为 token 替换版"""
import io
import re
import os

HERE = os.path.dirname(os.path.abspath(__file__))
P = os.path.join(HERE, 'gen_front.py')
s = io.open(P, encoding='utf-8').read()

start = s.index('def index_vue(')
end = s.index('# ============ 执行')

Q1 = chr(39)
NL = chr(10)


def build():
    L = []
    a = L.append
    a("def index_vue(mod, e):")
    a("    v = e['vname']")
    a("    Q1 = chr(39)")
    a("    NL = chr(10)")
    a("    search_items = NL.join(search_field(n, k, l, o) for (n, k, l, o) in e['fields'] if o.get('search'))")
    a("    cols = NL.join(table_col(n, k, l, o) for (n, k, l, o) in e['fields'])")
    a("    form_items = (NL.join(form_field(n, k, l, o) for (n, k, l, o) in e['fields']) if not e.get('readonly') else '')")
    a("    ops_audit = ''")
    a("    if e.get('audit'):")
    a("        ops_audit = ('          <el-button link type=\"primary\" @click=\"handleAudit(scope.row.id, ' + Q1 + '1' + Q1 + ')\" v-hasPermi=\"[' + Q1 + 'biz:' + mod + ':audit' + Q1 + ']\">通过</el-button>'")
    a("                      + NL + '          <el-button link type=\"warning\" @click=\"handleAudit(scope.row.id, ' + Q1 + '2' + Q1 + ')\" v-hasPermi=\"[' + Q1 + 'biz:' + mod + ':audit' + Q1 + ']\">驳回</el-button>')")
    a("    audit_fn = ''")
    a("    if e.get('audit'):")
    a("        audit_fn = (NL + '/** 审批操作 */'")
    a("            + NL + 'const handleAudit = async (id: number, status: string) => {'")
    a("            + NL + \"  const tip = status === '\" + '1' + \"' ? '\" + '确认通过该' + e['cn'] + '申请吗？' + \"' : '\" + '确认驳回该' + e['cn'] + '申请吗？' + \"'\"")
    a("            + NL + '  await message.confirm(tip)'")
    a("            + NL + '  await Api.audit' + v + '(id, status, status === ' + Q1 + '1' + Q1 + ' ? ' + Q1 + '审批通过' + Q1 + ' : ' + Q1 + '审批驳回' + Q1 + ')'")
    a("            + NL + \"  message.success('审批成功')\"")
    a("            + NL + '  await getList()'")
    a("            + NL + '}')")
    a("    create_call = ''")
    a("    if not e.get('readonly'):")
    a("        create_call = ('        <el-button type=\"primary\" plain @click=\"openForm(' + Q1 + 'create' + Q1 + ')\" v-hasPermi=\"[' + Q1 + 'biz:' + mod + ':create' + Q1 + ']\">'")
    a("                       + NL + '          <Icon icon=\"ep:plus\" class=\"mr-5px\" /> 新增'")
    a("                       + NL + '        </el-button>')")
    a("    update_btn = ''")
    a("    if not e.get('readonly'):")
    a("        update_btn = ('          <el-button link type=\"primary\" @click=\"openForm(' + Q1 + 'update' + Q1 + ', scope.row.id)\" v-hasPermi=\"[' + Q1 + 'biz:' + mod + ':update' + Q1 + ']\">修改</el-button>')")
    a("    del_btn = ('          <el-button link type=\"danger\" @click=\"handleDelete(scope.row.id)\" v-hasPermi=\"[' + Q1 + 'biz:' + mod + ':delete' + Q1 + ']\">删除</el-button>')")
    a("    form_dialog = ''")
    a("    if not e.get('readonly'):")
    a("        form_dialog = (NL + '  <!-- 表单弹窗 -->'")
    a("            + NL + '  <el-dialog v-model=\"dialogVisible\" :title=\"dialogTitle\" width=\"640px\">'")
    a("            + NL + '    <el-form ref=\"formRef\" :model=\"formData\" :rules=\"formRules\" label-width=\"100px\">'")
    a("            + NL + form_items")
    a("            + NL + '    </el-form>'")
    a("            + NL + '    <template #footer>'")
    a("            + NL + '      <el-button @click=\"dialogVisible = false\">取 消</el-button>'")
    a("            + NL + '      <el-button type=\"primary\" @click=\"submitForm\">确 定</el-button>'")
    a("            + NL + '    </template>'")
    a("            + NL + '  </el-dialog>')")
    a("    form_script = ''")
    a("    crud_calls = ''")
    a("    if not e.get('readonly'):")
    a("        rules = NL.join('  ' + n + ': [{ required: true, message: \"' + l + '不能为空\", trigger: \"blur\" }]' for (n, k, l, o) in e['fields'] if o.get('required')) or '  dummy: []'")
    a("        form_script = (NL + '/** 表单弹窗逻辑 */'")
    a("            + NL + 'const dialogVisible = ref(false)'")
    a("            + NL + \"const dialogTitle = ref('')\"")
    a("            + NL + \"const formType = ref('')\"")
    a("            + NL + 'const formLoading = ref(false)'")
    a("            + NL + 'const formRef = ref()'")
    a("            + NL + 'const formData = ref<Api.' + v + 'VO>({} as Api.' + v + 'VO)'")
    a("            + NL + 'const formRules = reactive({'")
    a("            + NL + rules")
    a("            + NL + '})'")
    a("            + NL + 'const openForm = (type: string, id?: number) => {'")
    a("            + NL + '  dialogVisible.value = true'")
    a("            + NL + '  dialogTitle.value = type === ' + Q1 + 'create' + Q1 + ' ? ' + Q1 + '新增' + e['cn'] + Q1 + ' : ' + Q1 + '修改' + e['cn'] + Q1")
    a("            + NL + '  formType.value = type'")
    a("            + NL + '  if (id) {'")
    a("            + NL + '    formLoading.value = true'")
    a("            + NL + '    Api.get' + v + '(id).then((data) => {'")
    a("            + NL + '      formData.value = data'")
    a("            + NL + '    }).finally(() => { formLoading.value = false })'")
    a("            + NL + '  } else {'")
    a("            + NL + '    formData.value = {} as Api.' + v + 'VO'")
    a("            + NL + '  }'")
    a("            + NL + '}'")
    a("        crud_calls = (NL + '/** 删除按钮操作 */'")
    a("            + NL + 'const handleDelete = async (id: number) => {'")
    a("            + NL + '  try {'")
    a("            + NL + '    await message.delConfirm()'")
    a("            + NL + '    await Api.delete' + v + '(id)'")
    a("            + NL + \"    message.success('删除成功')\"")
    a("            + NL + '    await getList()'")
    a("            + NL + '  } catch {}'")
    a("            + NL + '}'")
    a("            + NL + '/** 提交表单 */'")
    a("            + NL + \"const emit = defineEmits(['success'])\"")
    a("            + NL + 'const submitForm = async () => {'")
    a("            + NL + '  await formRef.value.validate()'")
    a("            + NL + '  formLoading.value = true'")
    a("            + NL + '  try {'")
    a("            + NL + '    if (formType.value === ' + Q1 + 'create' + Q1 + ') {'")
    a("            + NL + '      await Api.create' + v + '(formData as unknown as Api.' + v + 'VO)'")
    a("            + NL + \"      message.success('新增成功')\"")
    a("            + NL + '    } else {'")
    a("            + NL + '      await Api.update' + v + '(formData as unknown as Api.' + v + 'VO)'")
    a("            + NL + \"      message.success('修改成功')\"")
    a("            + NL + '    }'")
    a("            + NL + '    dialogVisible.value = false'")
    a("            + NL + \"    emit('success')\"")
    a("            + NL + '  } finally {'")
    a("            + NL + '    formLoading.value = false'")
    a("            + NL + '  }'")
    a("            + NL + '}')")
    a("    export_fn = (NL + '/** 导出按钮操作 */'")
    a("        + NL + 'const handleExport = async () => {'")
    a("        + NL + '  try {'")
    a("        + NL + '    await message.exportConfirm()'")
    a("        + NL + '    exportLoading.value = true'")
    a("        + NL + '    const data = await Api.export' + v + '(queryParams)'")
    a("        + NL + '    download.excel(data, ' + Q1 + e['cn'] + '.xls' + Q1 + ')'")
    a("        + NL + '  } catch {'")
    a("        + NL + '  } finally {'")
    a("        + NL + '    exportLoading.value = false'")
    a("        + NL + '  }'")
    a("        + NL + '}')")
    a("    qfields = ',\\n'.join('  ' + n + ': undefined' for (n, k, l, o) in e['fields'] if o.get('search'))")
    a("    tpl = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'front_index_template.vue.tpl'), encoding='utf-8').read()")
    a("    vue = (tpl.replace('__SEARCH__', search_items)")
    a("              .replace('__CREATE__', create_call)")
    a("              .replace('__PERM__', mod)")
    a("              .replace('__COLS__', cols)")
    a("              .replace('__UPDATE__', update_btn)")
    a("              .replace('__AUDIT__', ops_audit)")
    a("              .replace('__DEL__', del_btn)")
    a("              .replace('__FORM__', form_dialog)")
    a("              .replace('__API__', 'biz/' + mod)")
    a("              .replace('__VO__', v)")
    a("              .replace('__VNAME__', v)")
    a("              .replace('__QFIELDS__', qfields)")
    a("              .replace('__AUDITFN__', audit_fn)")
    a("              .replace('__FORMSCRIPT__', form_script)")
    a("              .replace('__CRUD__', crud_calls)")
    a("              .replace('__EXPORT__', export_fn))")
    a("    w('views/biz/' + mod + '/index.vue', vue)")
    a("")
    a("")
    a("# ============ 执行 ============")
    return NL.join(L)

new_fn = build()
s = s[:start] + new_fn + s[end:]
io.open(P, 'w', encoding='utf-8', newline='\n').write(s)
print('patched gen_front.py')
